/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/**
 * A service for adding additional monitors and handle instructions transfer.
 */
angular.module('client').factory('guacManageMonitor', ['$injector',
    function guacManageMonitor($injector) {

    // Required services
    const $window        = $injector.get('$window');
    const guacFullscreen = $injector.get('guacFullscreen');

    /**
     * Additionals monitors windows opened.
     * 
     * @type Object.<Number, Window>
     */
    const monitors = {};

    /**
     * The type of this monitor (default = primary).
     * 
     * @type String
     */
    let monitorType = "primary";

    /**
     * The current Guacamole client instance.
     * 
     * @type Guacamole.Client 
     */
    let client = null;

    /**
     * The display of the current Guacamole client instance.
     * 
     * @type Guacamole.Display
     */
    let display = null;

    /**
     * The broadcast channel used for communications between all windows.
     * 
     * @type BroadcastChannel
     */
    let broadcast = null;

    /**
     * The maximum number of secondary monitors allowed.
     *
     * @type Number
     */
    let maxSecondaryMonitors = 0;

    /**
     * Store the last additional monitor id.
     * 
     * @type Number
     */
    let lastMonitorId = 0;

    /**
     * Object containing monitors informations.
     *
     * @type Object
     * @property {Number} count
     *     The number of monitors, including the main window.
     * @property {Object.<Number, Number>} map
     *     A map of monitor id to position.
     * @property {Object.<Number, Object>} details
     *     Details of each browser window, including width, height, etc.
     * @property {Object.<Number, Object>} rendered
     *     Details of each rendered monitor, including width, height, etc.
     *     This is used to display what is expected by guacd.
     */
    let monitorsInfos = {
        count: 1,
        map: {},
        details: {},
        rendered: {},
    };

    const service = {};

    /**
     * Attributes of the monitor
     * 
     * @type Object.<Number>
     */
    service.monitorId = 0;

    /**
     * Unique identifier scoping the broadcast channel to this connection's
     * window group, preventing cross-talk between multiple connections open
     * in the same browser. Generated by the primary window and inherited by
     * secondary windows through their URL.
     *
     * @type String
     */
    let channelId = null;

    /**
     * The interval timer polling this window's screen position, if any.
     *
     * @type Number
     */
    let positionInterval = null;

    /**
     * Generate a random identifier for the broadcast channel.
     *
     * @returns {!String}
     *     A random, unguessable identifier.
     */
    const generateChannelId = function generateChannelId() {

        if (window.crypto?.randomUUID)
            return crypto.randomUUID();

        // Fallback for older browsers
        return Math.random().toString(36).substring(2)
             + Math.random().toString(36).substring(2);

    };

    /**
     * Init the monitor type and broadcast channel used for bidirectionnal
     * communications between primary and secondary monitor windows.
     *
     * @param {String} type
     *     The type of the monitor. "primary" if not given.
     *
     * @param {String} [channel]
     *     The channel identifier to join. Required for secondary monitors,
     *     which must join the channel created by their primary window.
     */
    service.init = function init(type, channel) {

        // Change the monitor type
        if (type) monitorType = type;

        if (monitorType == "primary") {
            guacFullscreen.onfullscreen = function onfullscreen(state) {
                service.pushBroadcastMessage('fullscreen', state);
            }
        }

        // Create broadcast if supported
        if (!service.supported())
            return;

        // The primary window creates the channel id; secondary windows join
        // the channel given in their URL
        if (channel)
            channelId = channel;
        else if (!channelId)
            channelId = generateChannelId();

        // init() may run again when the client route is re-entered - tear
        // down the previous channel and timer rather than leaking them
        if (broadcast)
            broadcast.close();
        if (positionInterval)
            clearInterval(positionInterval);

        broadcast = new BroadcastChannel('guac_monitors_' + channelId);

        /**
         * Handle messages sent by secondary monitors windows in
         * guac_monitors channel.
         *
         * @param {Event} e
         *     Received message event from guac_monitors channel.
         */
        broadcast.onmessage = messageHandlers[monitorType];

        // Check the window position every second and send a resize event if it
        // has changed
        positionInterval = setInterval(() => updatePosition(), 1000);

    };

    /**
     * Set the maximum number of secondary monitors allowed.
     *
     * @param {Number} secondaryMonitorsAllowed
     *     The maximum number of secondary monitors allowed.
     */
    service.setMaxSecondaryMonitors = function setMaxSecondaryMonitors(amount) {
        maxSecondaryMonitors = amount;
    }

    /**
     * Ensure that the limit of open monitors is not reached.
     * 
     * @returns {boolean}
     *     true when the limit of opened monitors is reached, false otherwise.
     */
    service.monitorLimitReached = function monitorLimitReached() {

        // Max open monitors allowed (add 1 for the primary monitor)
        const maxMonitors = maxSecondaryMonitors + 1;

        // Prevent opening of too many monitors
        return service.getMonitorCount() >= maxMonitors;

    };

    /**
     * Returns the identifier of this connection's broadcast channel group,
     * or null if init() has not yet run. Exposed so extensions (e.g. the
     * connection-bar extension) can open side channels scoped to the same group
     * of windows.
     *
     * @returns {String}
     *     The channel identifier, or null.
     */
    service.getChannelId = function getChannelId() {
        return channelId;
    };

    /**
     * Manual monitor arrangement, set through the arrangement panel. When
     * non-null, it overrides the automatic window-position-based ordering:
     * "order" is an array of secondary monitor ids in left-to-right order,
     * and "tops" maps monitor id to its vertical offset relative to the
     * primary monitor, in pixels.
     *
     * @type Object
     */
    let manualLayout = null;

    /**
     * Returns the current monitors information (details, rendered layout,
     * id-to-position map). Exposed read-only for extensions such as the
     * connection-bar extension's arrangement panel; callers must not modify it.
     *
     * @returns {Object}
     *     The current monitors information.
     */
    service.getMonitorsInfos = function getMonitorsInfos() {
        return monitorsInfos;
    };

    /**
     * Whether a manual arrangement is currently overriding the automatic
     * window-position-based monitor ordering.
     *
     * @returns {boolean}
     *     true if a manual arrangement is active.
     */
    service.isManualLayout = function isManualLayout() {
        return !!manualLayout;
    };

    /**
     * Applies a manual monitor arrangement. Ordering and vertical offsets
     * given here override the automatic ordering until clearManualLayout()
     * is called. The primary monitor is always position 0 and cannot move.
     *
     * @param {String[]} order
     *     Secondary monitor ids in the desired left-to-right order.
     *
     * @param {Object.<String, Number>} tops
     *     Map of secondary monitor id to vertical offset relative to the
     *     primary monitor, in pixels.
     */
    service.applyArrangement = function applyArrangement(order, tops) {

        manualLayout = {
            order : (order || []).map(String),
            tops  : tops || {},
        };

        updateMonitorsInfos();
        if (client)
            sendAllSizes(client);
        service.pushBroadcastMessage('monitorsInfos', monitorsInfos);

    };

    /**
     * Discards any manual arrangement, returning to automatic ordering by
     * actual window screen position. Positions resync on the next window
     * move or resize.
     */
    service.clearManualLayout = function clearManualLayout() {

        manualLayout = null;

        updateMonitorsInfos();
        if (client)
            sendAllSizes(client);
        service.pushBroadcastMessage('monitorsInfos', monitorsInfos);

    };

    /**
     * Overwrites the stored top offsets of manually-arranged monitors with
     * their manual values. Called whenever monitor details are updated, so
     * window moves/resizes cannot clobber a manual arrangement.
     */
    function applyManualTops() {

        if (!manualLayout)
            return;

        const primaryTop = monitorsInfos.details[0]?.top ?? 0;
        for (const id of Object.keys(manualLayout.tops)) {
            if (id !== '0' && monitorsInfos.details[id])
                monitorsInfos.details[id].top =
                        manualLayout.tops[id] + primaryTop;
        }

    }

    /**
     * Check if the browser supports the BroadcastChannel API.
     *
     * @returns {boolean}
     *     true if the BroadcastChannel API is supported, false otherwise.
     */
    service.supported = function supported() {

        if (!window.BroadcastChannel) {
            console.warn("BroadcastChannel is not supported by this browser.");
            return false;
        }

        return true;
    }

    /**
     * Handlers for instructions received on broadcast channel.
     */
    const messageHandlers = {

        "primary": function primary(message) {

            // Send size event to guacd
            if (message.data.size)
                service.sendSize(client, message.data.size);

            // Mouse state changed on secondary screen
            if (message.data.mouseState)
                client.sendMouseState(message.data.mouseState);

            // Key down on secondary screen
            if (message.data.keydown)
                client.sendKeyEvent(1, message.data.keydown);

            // Key up on secondary screen
            if (message.data.keyup)
                client.sendKeyEvent(0, message.data.keyup);

            // Additional window unloaded
            if (message.data.monitorClose)
                service.closeMonitor(message.data.monitorClose);

            // CTRL+ALT+SHIFT pressed on secondary window
            if (message.data.guacMenu && service.menuShown)
                service.menuShown();

        },

        "secondary": function secondaryMonitor(message) {
            
            // Run the client handler to draw display
            if (message.data.handler)
                client.runHandler(message.data.handler.opcode,
                                  message.data.handler.parameters);

            if (message.data.monitorsInfos)
                monitorsInfos = message.data.monitorsInfos;

            // Full screen mode instructions
            if (message.data.fullscreen !== undefined) {

                // setFullscreenMode require explicit user action
                if (message.data.fullscreen) {
                    if (service.openConsentButton) service.openConsentButton();
                }

                // Close fullscreen mode instantly
                else
                    guacFullscreen.setFullscreenMode(false);

            }
        }

    }

    /**
     * Add button to request user consent before enabling fullscreen mode to
     * comply with the setFullscreenMode requirements that require explicit
     * user action. The button is removed after a few seconds if the user does
     * not click on it.
     */
    service.openConsentButton = null;

    /**
     * Open or close Guacamole menu (ctrl+alt+shift).
     */
    service.menuShown = null;

    /**
     * Invoked on secondary windows whenever this monitor's offsets within
     * the combined display change. The window uses this to shift its
     * full-canvas replica so its own slice is in view.
     *
     * @param {!number} offsetX
     *     The X offset of this monitor within the combined display.
     *
     * @param {!number} offsetY
     *     The Y offset of this monitor within the combined display.
     */
    service.onoffsets = null;

    /**
     * Set the current Guacamole Client
     * 
     * @param {Guacamole.Client} guac_client
     *     The guacamole client where to send instructions.
     */
    service.setClient = function setClient(guac_client) {

        client  = guac_client;
        display = client.getDisplay();

        client.onmultimonlayout = onmultimonlayout;

        // Close all secondary monitors on client disconnect
        if (monitorType === "primary")
            client.ondisconnect = service.closeAllMonitors;

    }

    /**
     * Push broadcast message containing instructions that allows additional
     * monitor windows to draw display, resize window and more.
     * 
     * @param {!string} type
     *     The type of message (ex: handler, fullscreen, resize)
     *
     * @param {*} content
     *     The content of the message, can contain any type of serializable
     *     content.
     */
    service.pushBroadcastMessage = function pushBroadcastMessage(type, content) {

        // Channel not created (BroadcastChannel unsupported or init not run)
        if (!broadcast)
            return;

        // Send only if there are other monitors to receive this message
        if (monitorType === "primary" && service.getMonitorCount() <= 1)
            return;

        // Format message content
        const message = {
            [type]: content
        };

        // Send message on the broadcast channel
        broadcast.postMessage(message);

    };

    /**
     * Open an additional monitor window.
     */
    service.addMonitor = function addMonitor() {

        // New monitor id
        lastMonitorId++;

        // New window parameters. The channel id is passed in the URL so the
        // secondary window joins this connection's broadcast channel.
        const windowUrl  = './#/secondaryMonitor/' + lastMonitorId
                         + '/' + channelId;
        const windowId   = 'monitor' + lastMonitorId;
        const windowSize = 'width=800,height=600';

        // Open new window
        const monitorWindow = $window.open(windowUrl, windowId, windowSize);

        // The browser's popup blocker may deny the window; do not consume a
        // monitor slot when that happens, or the limit would be reached with
        // no windows actually open
        if (!monitorWindow) {
            lastMonitorId--;
            console.warn('Secondary monitor window was blocked. '
                + 'Allow popups for this site and try again.');
            return;
        }

        monitors[lastMonitorId] = monitorWindow;

    };

    /**
     * Close an additional monitor based on its id.
     * 
     * @param {!number} monitorId
     *     The monitor ID to close.
     */
    service.closeMonitor = function closeMonitor(monitorId) {

        // Monitor not found or already closed
        if (!monitors[monitorId])
            return;

        // Close monitor
        if (!monitors[monitorId].closed)
            monitors[monitorId].close();

        // Delete monitor
        delete monitors[monitorId];

        // Notify guacd that a monitor has been closed
        service.sendSize(client, {
            width: 0,
            height: 0,
            top: 0,
            monitorId: monitorId,
        });

    }

    /**
     * Close all additional monitors.
     */
    service.closeAllMonitors = function closeAllMonitors() {

        // Loop on all existing monitors
        for (const key in monitors)
            service.closeMonitor(key);

        // A manual arrangement does not outlive its monitors
        manualLayout = null;

    };

    /**
     * Get open monitors count.
     *
     * @returns {!number}
     *     Actual count of monitors.
     */
    service.getMonitorCount = function getMonitorCount() {
        // Return additionals monitors count + 1 for the main window
        return Object.keys(monitors).length + 1;
    };

    /**
     * Send size event to guacd and update monitorsInfos object.
     *
     * @param {Guacamole.Client} requestedClient
     *     The Guacamole client to send the size to. This is needed for
     *     connection groups with multiple clients.
     * @param {Object} size
     *     The size object containing width, height, top and monitorId.
     */
    service.sendSize = function sendSize(requestedClient, size) {

        const monitorPosition = monitorsInfos.map[size.monitorId];

        updateMonitorsInfos({
            id:     size.monitorId,
            width:  size.width,
            height: size.height,
            left:   size.left,
            top:    size.top,
        });

        // Monitor has been closed
        if (size.width === 0 || size.height === 0)
            requestedClient.sendSize(0, 0, monitorPosition, 0);

        // Send new size to guacd
        else
            sendAllSizes(requestedClient);

        // Push informations to all monitors
        service.pushBroadcastMessage('monitorsInfos', monitorsInfos);

    }

    /**
     * Get the X offset of the current monitor. The X offset is the
     * total width of all previous monitors.
     *
     * @return {number}
     *     The X offset of the current monitor, in pixels.
     */
    service.getOffsetX = function getOffsetX() {

        const rendered = monitorsInfos.rendered[service.monitorId];

        // Not yet part of a rendered layout
        if (!rendered || rendered.left == null)
            return 0;

        // Use the absolute left coordinate reported by guacd, normalized
        // against the leftmost rendered monitor. Unlike summing widths by
        // position, this stays correct for vertical arrangements and any
        // layout with gaps.
        let minLeft = Infinity;
        for (const other of Object.values(monitorsInfos.rendered)) {
            if (other?.left != null && other.left < minLeft)
                minLeft = other.left;
        }

        return rendered.left - (minLeft === Infinity ? 0 : minLeft);
    }

    /**
     * Get the Y offset of the current monitor. The monitor displayed on the
     * highest position (lowest top value) will have an offset of 0 and for
     * other monitors, the offset is the top value of the monitor minus the top
     * value of the highest monitor (lowest top offset).
     * This is used to calculate the Y offset to draw operations and mouse
     * events.
     *
     * @return {number}
     *     The Y offset of the current monitor, in pixels.
     */
    service.getOffsetY = function getOffsetY() {

        // Vertical arrangement is locked (see getTopOffset) - all monitors
        // share the same top edge, so the vertical offset is always 0
        return 0;

    }

    /**
     * Send the size of all monitors to guacd. This is used to update the
     * monitor sizes in guacd when a new monitor is added or updated.
     *
     * This function loops through all monitors and sends their sizes to guacd
     * using the client.sendSize method. The size includes width, height,
     * monitor position and top offset.
     *
     * @param {Guacamole.Client} requestedClient
     *     The Guacamole client to send the sizes to.
     */
    function sendAllSizes(requestedClient) {
        // Loop through all monitors and send their sizes to guacd
        for (const [id, details] of Object.entries(monitorsInfos.details)) {
            requestedClient.sendSize(
                details.width,
                details.height,
                monitorsInfos.map[id],
                getTopOffset(id, details.top)
            );
        }
    }

    /**
     * Get the top offset of the given monitor id and top value based on the
     * primary monitor's top value. The top offset is the difference between the
     * top value of the monitor and the top value of the primary monitor.
     * This is used to calculate the Y offset to send to guacd.
     *
     * @param {number} id
     *     The id of the monitor.
     * @param {number} top
     *     The top value of the monitor.
     *
     * @return {number}
     *     The top offset of the monitor, in pixels.
     */
    function getTopOffset(id, top) {

        // Vertical arrangement is LOCKED for now: offsets are always sent
        // as 0, so monitors form a single top-aligned row. Vertical offsets
        // caused partially cut-off monitor rendering; revisit alongside the
        // upstream vertical-reordering work before re-enabling.
        return 0;

    }

    /**
     * Get the lowest top value of all monitors. This is used to calculate the
     * Y offset of the current monitor.
     *
     * @return {number}
     *     The lowest top value of all monitors, in pixels.
     */
    function getLowestTopOffset() {
        let lowestTopValue = monitorsInfos.rendered[0]?.top ?? 0;

        // Loop through all monitors to find the highest monitor
        for (const [_, rendered] of Object.entries(monitorsInfos.rendered)) {
            if (rendered?.top < lowestTopValue) {
                lowestTopValue = rendered.top;
            }
        }

        return lowestTopValue;
    }

    /**
     * Update monitorsInfos object with current monitors count and map.
     *
     * @param {Object} monitorDetails
     *     Optional monitor details to update the monitorsInfos object.
     */
    function updateMonitorsInfos(monitorDetails) {

        monitorsInfos.count = service.getMonitorCount();

        // Set monitor details if provided
        if (monitorDetails) {

            // If width or height is 0, remove monitor details
            if (monitorDetails.width === 0 || monitorDetails.height === 0) {
                delete monitorsInfos.details[monitorDetails.id];
                delete monitorsInfos.rendered[monitorDetails.id];
            }
            // Update or add monitor details
            else {
                const monitorId = monitorDetails.id;
                monitorsInfos.details[monitorId] = {
                    width:  monitorDetails.width,
                    height: monitorDetails.height,
                    top:    monitorDetails.top,
                    left:   monitorDetails.left,
                };
            }
        }

        // A manual arrangement (set through the arrangement panel) overrides
        // the automatic window-position-based ordering entirely
        if (manualLayout) {

            applyManualTops();

            monitorsInfos.map = {};
            let manualPosition = 0;
            for (const id of manualLayout.order)
                if (id === '0' || monitors[id])
                    monitorsInfos.map[id] = manualPosition++;

            // The main window and any monitors opened after the arrangement
            // was made append at the end in opening order
            if (!('0' in monitorsInfos.map))
                monitorsInfos.map[0] = manualPosition++;
            for (const id of Object.keys(monitors))
                if (!(id in monitorsInfos.map))
                    monitorsInfos.map[id] = manualPosition++;

            return;

        }

        // Order all monitors - including the main window - by their reported
        // screen position (left, then top) so the remote layout matches
        // where the windows actually sit, letting the user rearrange
        // monitors by dragging the windows. Monitors that have not yet
        // reported a position keep their opening order and sort last.
        const sorted = ['0', ...Object.keys(monitors)]
            .map((id, index) => ({ id: id, index: index,
                                   details: monitorsInfos.details[id] }))
            .sort((a, b) => {
                const aPlaced = a.details && a.details.left != null;
                const bPlaced = b.details && b.details.left != null;
                if (aPlaced && bPlaced)
                    return (a.details.left - b.details.left)
                        || (a.details.top  - b.details.top)
                        || (a.index - b.index);
                if (aPlaced) return -1;
                if (bPlaced) return 1;
                return a.index - b.index;
            });

        // Rebuild the id => position map contiguously in sorted order. Note
        // the main window is NOT pinned to position 0: whichever monitor is
        // leftmost occupies slot 0 and is flagged as the remote session's
        // primary monitor by guacd.
        monitorsInfos.map = {};
        let monitorPosition = 0;
        for (const monitor of sorted)
            monitorsInfos.map[monitor.id] = monitorPosition++;

    };

    /**
     * Check if the window position has changed since the last check.
     * This is used to avoid unnecessary updates.
     *
     * @returns {boolean}
     *     True if the position has changed, false otherwise.
     */
    function positionHasChanged() {
        const monitorDetails = monitorsInfos.details[service.monitorId];

        // Monitor not initialized
        if (!monitorDetails)
            return false;

        return monitorDetails.left !== window.screenX
            || monitorDetails.top  !== window.screenY;
    }

    /**
     * Trigger a resize event if the window position has changed.
     */
    function updatePosition() {

        // Window positions are irrelevant while a manual arrangement is
        // active - the panel's layout must not be clobbered by window moves
        if (manualLayout)
            return;

        if (!positionHasChanged() || !client)
            return;

        const monitorDetails = monitorsInfos.details[service.monitorId];

        // Update the position of the monitor
        monitorDetails.left      = window.screenX ?? 0;
        monitorDetails.top       = window.screenY ?? 0;
        monitorDetails.monitorId = service.monitorId;

        // Send size event to guacd and update monitorsInfos if this is the
        // primary monitor
        if (monitorType === "primary") {
            service.sendSize(client, monitorDetails);
            return;
        }

        // Send broadcast message to primary monitor if this is a secondary
        // monitor
        service.pushBroadcastMessage('size', monitorDetails);
    }

    /**
     * Handle the multimonitor layout event. This is used to update the
     * monitorsInfos object when the layout changes.
     *
     * @param {Object} layout
     *     An object describing the layout of monitors.
     */
    /**
     * Count of consecutive layout updates in which each monitor was absent,
     * keyed by monitor id. A monitor is only closed after several
     * consecutive absences: a layout emitted concurrently with adding a
     * monitor may legitimately not include it yet.
     *
     * @type Object.<Number, Number>
     */
    const layoutMisses = {};

    /**
     * The number of consecutive layout updates a monitor must be absent
     * from before it is considered closed by guacd.
     *
     * @type Number
     */
    const LAYOUT_MISS_LIMIT = 8;

    function onmultimonlayout(layout) {
        if (!layout)
            return;

        for (const [id, pos] of Object.entries(monitorsInfos.map)) {

            // If the monitor is repeatedly missing from the layout, it is
            // not known by guacd anymore, so we close it
            if (!layout[pos]) {
                layoutMisses[id] = (layoutMisses[id] ?? 0) + 1;
                if (layoutMisses[id] >= LAYOUT_MISS_LIMIT) {
                    delete layoutMisses[id];
                    service.closeMonitor(id);
                }
                continue;
            }

            // Monitor present again - reset its miss count
            delete layoutMisses[id];

            if (!monitorsInfos.rendered[id])
                monitorsInfos.rendered[id] = {};
                
            // Update the monitor details
            monitorsInfos.rendered[id].width  = layout[pos].width;
            monitorsInfos.rendered[id].height = layout[pos].height;
            monitorsInfos.rendered[id].top    = layout[pos].top;
            monitorsInfos.rendered[id].left   = layout[pos].left;

            // Clamp the display to this monitor's size only on the primary
            // window - secondary windows render the FULL combined display
            // (see below)
            if (monitorType === "primary" && id === String(service.monitorId)) {
                display.setMonitorSize(
                    monitorsInfos.rendered[id].width,
                    monitorsInfos.rendered[id].height,
                );
            }

        }

        // Secondary windows keep a full-canvas replica of the combined
        // display and shift it into view with CSS (via onoffsets) instead of
        // cropping at draw time. Cropping broke "copy" instructions whose
        // source region lies in another monitor's slice - the source data
        // simply does not exist on a cropped canvas, leaving black
        // rectangles until the region is repainted.
        if (monitorType === "secondary") {
            client.offsetX = 0;
            client.offsetY = 0;
            if (service.onoffsets)
                service.onoffsets(service.getOffsetX(), service.getOffsetY());
        }

        // The primary window crops at draw time as before
        else {
            client.offsetX = service.getOffsetX();
            client.offsetY = service.getOffsetY();
        }

    }

    // Close additional monitors when window is unloaded
    $window.addEventListener('unload', service.closeAllMonitors);

    return service;

}]);
